---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    labels:
      - 'custom.project=kafkajs-zstd'
      - 'custom.service=kafka'
    depends_on:
      - zookeeper
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'

  kafka-mini-project:
    build:
      context: .
      dockerfile: Dockerfile
    image: brennosaudeid/kafka-discord:latest
    depends_on:
      - kafka
    ports:
      - 3000:3000
    environment:
      KAFKA_CLIENT_ID: DISCORD
      KAFKA_BROKERS: kafka:9094
      PORT: 3000
  kafka-mini-consumer:
    image: brennosaudeid/kafka-discord-consumer:latest
    depends_on:
      - kafka-mini-project
    ports:
      - 3001:3001
    environment:
      KAFKA_CLIENT_ID: DISCORD
      KAFKA_BROKERS: kafka:9094
      GROUP_ID: NPM
      DISCORD_URL: https://discord.com/api/webhooks/923614009406677062/RCk2U5XXHZEaqiF9CMuMXHtV8_Z_r5oBSLZK5SbqUGlPXUld9OmC-neX9dHRgI38YwOm
      TOPICS: NPM_PACKAGE
      PORT: 3001